name: GitHub pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.0
      - name: Set safe directory for Git
        uses: actions/setup-safe-directory@v1
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
